### ISSUE TITLE
Upper Keywords

### ISSUE THREAD

**Issue by volker-raschek** [zabel-xyz/plsql-language#50] opened 2018-06-19 08:22 UTC
Hello, 
I have a feature request. So maybe it's possible to implement an option in the settings to write keywords in upper case?

For example
```sql
begin

end;
```
to 
```sql
BEGIN

END;
```

Volker

**Comment by zabel-xyz** [comment] 2018-06-20 10:52
duplicate of issue #14

**Closed by zabel-xyz** 2018-06-20 10:52 UTC
Labels: duplicate
